### ISSUE TITLE
Yii2, uploading 2 file in same test use same $file value

### ISSUE THREAD

**Issue by vinpel** [Codeception/Codeception#4638]
#### What are you trying to achieve?
Sending 2 file via Upload

#### What do you get instead?
The 1st upload is Ok, the second call use the same file[] value.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
./vendor/bin/codecept run functional AjoutTraitementCest:testContenuPreparation -vv
Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

  [Db] Connected to yii2_basic_tests
  [Db] Connected to yii2_basic_tests
  [Db] No SQL loaded, loading dump skipped

Functional Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Filesystem, Asserts, Yii2, REST, Db
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
AjoutTraitementCest: Test contenu preparation
Signature: AjoutTraitementCest:testContenuPreparation
Test: tests/functional/AjoutTraitementCest.php:testContenuPreparation
Scenario --
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=127.0.0.1;dbname=yii2_basic_tests'
 I have fixtures {"HistoriqueSystem":{"class":"mySociety\\modules\\historique\\tests\\fixtures\\HistoriqueSystem"},"HistoriqueWebService":{"class":"mySociety\\modules\\historique\\tests\\fixtures\\Hi...}
 I am on route "site/login"
  [Request Headers] []
  [Page] /site/login
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"content-type":["text/html; charset=UTF-8"]}
 I am logged in as 1
  [yii\web\Session::open] 'Session started'
  [yii\web\User::login] 'User \'1\' logged in from  with duration 0.'
 I am on page "/"
  [Request Headers] []
  [yii\web\Session::init] 'Session is already started'
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=127.0.0.1;dbname=yii2_basic_tests'
  [Page] /
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"content-type":["text/html; charset=UTF-8"]}
 I see "Se déconnecter"
 I see "admin","a"
 I delete header "file"
 I send post "/ajout-traitement/upload",[],{"file":{"name":"pdf_ok.pdf","type":"application\/pdf","error":0,"size":4020511,"tmp_name":"\/data\/htdocs\/tests\/_data\/upload\/pdf_ok.pdf"}}
  [Request] POST /ajout-traitement/upload []
   [=========> (string)$this->connectionModule->_request \$files value :
  Array
  (
      [file] => Array
          (
              [name] => pdf_ok.pdf
              [type] => application/pdf
              [error] => 0
              [size] => 4020511
              [tmp_name] => /data/htdocs/tests/_data/upload/pdf_ok.pdf
          )

  )

   =========]
  [Request Headers] []
  [yii\web\Session::init] 'Session is already started'
  yii\web\UploadedFile Object
  (
      [name] => pdf_ok.pdf
      [tempName] => /data/htdocs/tests/_data/upload/pdf_ok.pdf
      [type] => application/pdf
      [size] => 4020511
      [error] => 0
  )

  [Page] /ajout-traitement/upload
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"content-type":["text/html; charset=UTF-8"]}
  [Response] ok
 I see response code is 200
 I grab response
 I assert equals "ok","ok"
 I delete header "file"
 I send post "/ajout-traitement/upload",[],{"file":{"name":"doc.xlsm","type":"application\/xlsx","error":0,"size":35124,"tmp_name":"\/data\/htdocs\/tests\/_data\/upload\/doc.xlsm"}}
  [Request] POST /ajout-traitement/upload []
   [=========> (string)$this->connectionModule->_request \$files value :
  Array
  (
      [file] => Array
          (
              [name] => doc.xlsm
              [type] => application/xlsx
              [error] => 0
              [size] => 35124
              [tmp_name] => /data/htdocs/tests/_data/upload/doc.xlsm
          )

  )

   =========]
  [Request Headers] []
  [yii\web\Session::init] 'Session is already started'
  yii\web\UploadedFile Object
  (
      [name] => pdf_ok.pdf
      [tempName] => /data/htdocs/tests/_data/upload/pdf_ok.pdf
      [type] => application/pdf
      [size] => 4020511
      [error] => 0
  )

  [Page] /ajout-traitement/upload
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"content-type":["text/html; charset=UTF-8"]}
  [Response] ok
 I see response code is 200
 I grab response
 I assert equals "ok","ok"
 I have http header "Content-Type","multipart/form-data"
 I am on page "/ajout-traitement"
  [Request Headers] {"Content-Type":"multipart/form-data"}
  [yii\web\Session::init] 'Session is already started'
  [Page] /ajout-traitement
  [Response] 200
  [Request Cookies] []
  [Response Headers] {"content-type":["text/html; charset=UTF-8"]}
 I see "pdf_ok.pdf"
 I see "doc.xlsm"
 FAIL

```
> Provide test source code if related

```php
<?php
/**
  * [testUpload description]
  * @param  FunctionalTester $I [description]
  * @return [type]              [description]
  */
    private function UploadOk(FunctionalTester $I, $nomFichier, $mimeType)
    {
        $I->deleteHeader('file');
        $I->sendPOST(
        '/ajout-traitement/upload',
        [],
        [
        'file' => [
          'name'     => $nomFichier,
          'type'     => $mimeType,
          'error'    => UPLOAD_ERR_OK,
          'size'     => filesize(codecept_data_dir( 'upload/'.$nomFichier)),
          'tmp_name' => codecept_data_dir( 'upload/'.$nomFichier),
        ]
        ]
        );
        $I->seeResponseCodeIs(200);
        $reponse=$I->grabResponse();
        $I->assertEquals("ok", $reponse );
    }
  public function testContenuPreparation(FunctionalTester $I)
    {
        $this->UploadOk($I, 'pdf_ok.pdf', 'application/pdf');
        $this->UploadOk($I, 'doc.xlsm', 'application/xlsx');
        $I->haveHttpHeader('Content-Type', 'multipart/form-data');
        $I->amOnPage('/ajout-traitement');
        $I->see('pdf_ok.pdf');
        $I->see('doc.xlsm');
    }
?>
```
### Details

* Codeception version: 2.3.6
* PHP Version: 7.0.6-dev
* ***Yii2 version :2.0.13.1***
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
```
behat/gherkin                                 v4.4.5             Gherkin DSL parser for PHP 5.3
block8/php-docblock-checker                   1.3.4              A simple tool for checking that your PHP classes and methods use docblocks.
bower-asset/bootstrap                         v3.3.7
bower-asset/bootstrap-datepicker              v1.6.4
bower-asset/bootstrap-select                  v1.12.4
bower-asset/bootstrap-switch                  v3.3.3
bower-asset/bootstrap-touchspin               3.1.2
bower-asset/c3                                v0.4.18
bower-asset/d3                                v3.5.17
bower-asset/datatables                        1.10.16
bower-asset/datatables-colreorder             1.3.3
bower-asset/datatables-colvis                 1.1.2
bower-asset/dropzone                          v5.1.1
bower-asset/eonasdan-bootstrap-datetimepicker 4.17.47
bower-asset/fastclick                         v0.6.11
bower-asset/font-awesome                      v4.7.0
bower-asset/google-code-prettify              v1.0.5
bower-asset/inputmask                         3.3.10
bower-asset/jquery                            3.2.1
bower-asset/jquery-ui                         1.12.1
bower-asset/matchheight                       0.7.2
bower-asset/moment                            2.18.1
bower-asset/moment-timezone                   0.5.14
bower-asset/patternfly                        v3.30.0
bower-asset/patternfly-bootstrap-combobox     1.1.7
bower-asset/patternfly-bootstrap-treeview     v2.1.5
bower-asset/punycode                          v1.3.2
bower-asset/switchery                         0.8.2
bower-asset/transitionize                     0.0.3
bower-asset/typeahead.js                      v0.11.1
bower-asset/yii2-pjax                         2.0.7.1
cebe/markdown                                 1.1.2              A super fast, highly extensible markdown parser for PHP
codeception/base                              2.3.6              BDD-style testing framework
codeception/specify                           0.4.6              BDD code blocks for PHPUnit and Codeception
codeception/verify                            0.3.3              BDD assertion library for PHPUnit
digitickets/lalit                             2.0.0              GitHub copy of LaLit's XML2Array and Array2XML
doctrine/instantiator                         1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
ezyang/htmlpurifier                           v4.9.3             Standards compliant HTML filter written in PHP
fzaninotto/faker                              v1.7.1             Faker is a PHP library that generates fake data for you.
guzzlehttp/psr7                               1.4.2              PSR-7 message implementation that also provides common utility methods
ircmaxell/random-lib                          v1.0.0             A Library For Generating Secure Random Numbers
ircmaxell/security-lib                        1.0.0              A Base Security Library
mtdowling/cron-expression                     v1.2.1             CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
myclabs/deep-copy                             1.7.0              Create deep copies (clones) of your objects
nikic/php-parser                              v3.1.2             A PHP parser written in PHP
phpdocumentor/reflection-common               1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock             3.3.2              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a ...
phpdocumentor/type-resolver                   0.4.0
phpoffice/phpexcel                            1.8.1              PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpoffice/phpspreadsheet                      dev-master 7d4dc74 PHPSpreadsheet - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpspec/php-diff                              v1.1.0             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                              v1.7.2             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                     4.0.8              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                     1.4.2              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                     1.2.1              Simple template engine.
phpunit/php-timer                             1.0.9              Utility class for timing
phpunit/php-token-stream                      1.4.11             Wrapper around PHP's tokenizer extension.
phpunit/phpunit                               5.7.25             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects                  3.4.4              Mock Object library for PHPUnit
psr/http-message                              1.0.1              Common interface for HTTP messages
psr/log                                       1.0.2              Common interface for logging libraries
psr/simple-cache                              1.0.0              Common interfaces for simple caching
sebastian/code-unit-reverse-lookup            1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator                          1.2.4              Provides the functionality to compare PHP values for equality
sebastian/diff                                1.4.3              Diff implementation
sebastian/environment                         2.0.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                            2.0.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state                        1.1.1              Snapshotting of global state
sebastian/object-enumerator                   2.0.1              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context                   2.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations                 1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                             2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
stecman/symfony-console-completion            0.7.0              Automatic BASH completion for Symfony Console Component based applications.
swiftmailer/swiftmailer                       v5.4.8             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                           v3.3.13            Symfony BrowserKit Component
symfony/console                               v3.3.13            Symfony Console Component
symfony/css-selector                          v3.3.13            Symfony CssSelector Component
symfony/debug                                 v3.3.13            Symfony Debug Component
symfony/dom-crawler                           v3.3.13            Symfony DomCrawler Component
symfony/event-dispatcher                      v3.3.13            Symfony EventDispatcher Component
symfony/finder                                v3.3.13            Symfony Finder Component
symfony/polyfill-mbstring                     v1.6.0             Symfony polyfill for the Mbstring extension
symfony/yaml                                  v3.3.13            Symfony Yaml Component
toxor88/yii2-widget-switchery                 1.0                Enhanced Yii2 wrapper for the Switchery.js plugin.
vinpel/yii2-dropzone                          v1.0.5             DropzoneJs Extention for Yii2 based on Parminder repo
webmozart/assert                              1.2.0              Assertions to validate method input/output with nice error messages.
yii2assets/yii2-pdfjs                         1.0.2              Yii2 Extension  pdf.js Portable Document Format (PDF) viewer
yiisoft/yii2                                  2.0.13.1           Yii PHP Framework Version 2
yiisoft/yii2-bootstrap                        2.0.7              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer                         2.0.5              The composer plugin for Yii extension installer
yiisoft/yii2-debug                            2.0.12             The debugger extension for the Yii framework
yiisoft/yii2-faker                            2.0.3              Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                              2.0.5              The Gii extension for the Yii framework
yiisoft/yii2-jui                              2.0.6              The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer                      2.0.7              The SwiftMailer integration for the Yii framework
```
* Suite configuration:

```yml
# paste suite config here
class_name: FunctionalTester
modules:
    enabled:
      - Filesystem
      - Asserts
      - Yii2
      - REST:
          depends: Yii2

```

to be able to view passed argument, i have edited the ***base\src\Codeception\Module\Rest.php*** file :

```php
            } else {
                $this->debugSection("Request", "$method $url " . json_encode($parameters));
                $files = $this->formatFilesArray($files);
            }
            \Codeception\Util\Debug::debug(' [=========> (string)$this->connectionModule->_request \$files value :');
            \Codeception\Util\Debug::debug($files);
            \Codeception\Util\Debug::debug(' =========]');

            $this->response = (string)$this->connectionModule->_request($method, $url, $parameters, $files);
```

**Comment by vinpel** [comment]
The Yii2 object in functional test appear to not be not properly reset.

the $_FILE is correct but second upload /web/UploadedFile.php#L206 doesn't find null.

In the model handling the upload, adding a reset command solve my issue :
```php
        UploadedFile::reset();
        $this->uploadInstance = UploadedFile::getInstanceByName("file");
```

This code reset is only needed for the test.
If i comment the following line, the test pass too.

https://github.com/yiisoft/yii2/blob/6f896ce9173fb7de3a898b7c03439917828ae342/framework/web/UploadedFile.php#L206/web/UploadedFile.php#L206

**Comment by SamMousa** [comment]
@vinpel could you confirm my PR fixes your issue?

**Comment by Naktibalda** [comment]
Fixed by #5043

**Comment by BenasPaulikas** [comment]
@Naktibalda nice name. Greetings from Lithuania
This issue was closed.
But PR https://github.com/Codeception/Codeception/pull/5043/changes wasn't merged?
I believe it was a mistake to close this issue

I'm still experiencing this issue. Adding this manually helps.
>  UploadedFile::reset();

```

codeception/codeception                 5.3.5
codeception/lib-asserts                 2.2.0
codeception/lib-innerbrowser            3.1.3
codeception/lib-web                     1.0.7
codeception/lib-xml                     1.1.1
codeception/module-asserts              3.2.1
codeception/module-filesystem           3.0.2
codeception/module-phpbrowser           4.0.0
codeception/module-rest                 dev-master 596817f
codeception/module-webdriver            3.2.2
codeception/module-yii2                 1.1.12
codeception/stub                        4.3.0
codeception/verify                      3.4.0
```

**Comment by SamMousa** [comment]
Can you create a new PR?
